apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: flasktest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flasktest
  template:
    metadata:
      labels:
        app: flasktest
    spec:
      containers:
        - name: flasktest
          image: stayc/test:5
          imagePullPolicy: Always
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: flasktest
  ports:
    - port: 80
      targetPort: 5000
