apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: lb-service
  template:
    metadata:
      labels:
        app: lb-service
    spec:
      containers:
      - image: stayc/test:1
        name: lb-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: lb-service
