apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: flasktest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flasktest
  template:
    metadata:
      labels:
        app: flasktest
    spec:
      containers:
        - name: flasktest
          image: stayc/test:1
          imagePullPolicy: Always
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  selector:
    app: flasktest
  ports:
    - port: 80
      targetPort: 5000
